#!/usr/bin/env python3
"""Fetch TTS from Cartesia, emit raw PCM .bin and a C uint8_t[] header.

Usage:  python3 gen_tts.py
Reads CARTESIA_API_KEY from ../../../.env.
"""
import os, sys, pathlib, httpx

ROOT = pathlib.Path(__file__).resolve().parents[3]
ENV  = ROOT / ".env"
OUT  = pathlib.Path(__file__).resolve().parent / "tts_clips.h"

for line in ENV.read_text().splitlines():
    if line.startswith("CARTESIA_API_KEY="):
        os.environ["CARTESIA_API_KEY"] = line.split("=", 1)[1].strip()

KEY = os.environ["CARTESIA_API_KEY"]
VOICE = "f786b574-daa5-4673-aa0c-cbe3e8534c02"

CLIPS = [
    ("CLIP_SHORT",  "Testing, one, two, three."),
    ("CLIP_MEDIUM", "Hello — this is Helios. Let's see how this playback sounds."),
]

def synth(text: str) -> bytes:
    r = httpx.post(
        "https://api.cartesia.ai/tts/bytes",
        headers={
            "Authorization": f"Bearer {KEY}",
            "Cartesia-Version": "2026-01-12",
            "Content-Type": "application/json",
        },
        json={
            "model_id": "sonic-3-2026-01-12",
            "transcript": text,
            "voice": {"mode": "id", "id": VOICE},
            "output_format": {"container": "raw", "encoding": "pcm_s16le", "sample_rate": 24000},
            "language": "en",
        },
        timeout=30.0,
    )
    r.raise_for_status()
    return r.content

def emit(name: str, pcm: bytes, fh):
    fh.write(f"// {name}: {len(pcm)} bytes, {len(pcm)/2/24000:.2f}s @ 24kHz s16le mono\n")
    fh.write(f"static const uint32_t {name}_LEN = {len(pcm)};\n")
    fh.write(f"static const uint8_t {name}[] = {{\n    ")
    for i, b in enumerate(pcm):
        fh.write(f"0x{b:02x},")
        if (i + 1) % 16 == 0:
            fh.write("\n    ")
    fh.write("\n};\n\n")

with OUT.open("w") as fh:
    fh.write("// Auto-generated by gen_tts.py — raw PCM s16le mono @ 24 kHz.\n")
    fh.write("#pragma once\n#include <stdint.h>\n\n")
    for name, text in CLIPS:
        print(f"Fetching {name!r} = {text!r}")
        pcm = synth(text)
        print(f"  got {len(pcm):,} bytes ({len(pcm)/2/24000:.2f}s)")
        # Save raw .bin too for debugging
        (OUT.parent / f"{name.lower()}.pcm").write_bytes(pcm)
        emit(name, pcm, fh)

print(f"\nWrote {OUT}  ({OUT.stat().st_size:,} bytes)")
