#!/usr/bin/env python3
"""One-time OTA HMAC-SHA256 secret generator.

Writes:
  ~/.helios/ota_sign.key                           — 32-byte HMAC secret (hex)
  firmware/diag/camera_ota/ota_pubkey.h            — same 32 bytes as C header

Usage:  python3 scripts/gen_ota_key.py [--force]

The secret is the trust root for all future signed OTA builds. If
lost or rotated, the ESP can no longer accept new firmware over-the-air
until the matching embedded key is updated via USB reflash.

Threat model note: HMAC is symmetric. An attacker who dumps flash gets
the secret and can forge signed firmware. This is acceptable because
anyone with physical flash access can already reflash via USB directly.
"""

import argparse
import os
import pathlib
import secrets
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
PRIV = pathlib.Path.home() / ".helios" / "ota_sign.key"
PUB_HEADER = ROOT / "firmware" / "diag" / "camera_ota" / "ota_pubkey.h"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true",
                    help="overwrite existing key (invalidates all current signed builds)")
    args = ap.parse_args()

    PRIV.parent.mkdir(parents=True, exist_ok=True)
    if PRIV.exists() and not args.force:
        print(f"refusing to overwrite {PRIV} — pass --force to replace", file=sys.stderr)
        return 2

    key = secrets.token_bytes(32)
    PRIV.write_text(key.hex() + "\n")
    os.chmod(PRIV, 0o600)

    lines = [
        "/* Auto-generated by scripts/gen_ota_key.py — do not edit by hand. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "/* HMAC-SHA256 secret for verifying signed OTA uploads + SD recovery bins.",
        " * Matching secret: ~/.helios/ota_sign.key (NOT in repo). */",
        "static const uint8_t OTA_HMAC_KEY[32] = {",
    ]
    for i in range(0, 32, 8):
        chunk = ", ".join(f"0x{b:02x}" for b in key[i:i+8])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("#define OTA_SIG_LEN 32")
    lines.append("")
    PUB_HEADER.write_text("\n".join(lines))

    print(f"secret: {PRIV}  (chmod 600)")
    print(f"header: {PUB_HEADER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
