[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
    -Wno-error=maybe-uninitialized
board_build.esp-idf.sdkconfig_defaults = sdkconfig.defaults
board_build.partitions = partitions.csv
